window.CBSE_BANK={
Maths:[
{text:'Euclid division lemma has the form',options:['a=bq+r, 0≤r<b','a=b+r','a=br','a=q+r'],answer:0,type:'MCQ',marks:1,chapter:'Real Numbers',explanation:'a=bq+r with 0≤r<b.'},
{text:'For x²−5x+6, the sum of zeroes is',options:['6','5','−5','−6'],answer:1,type:'MCQ',marks:1,chapter:'Polynomials',explanation:'Sum of zeroes is −b/a=5.'},
{text:'2x+3y=7 and 4x+6y=14 represent',options:['intersecting','parallel','coincident','perpendicular'],answer:2,type:'MCQ',marks:1,chapter:'Pair of Linear Equations',explanation:'Second equation is twice the first.'},
{text:'For x²−7x+10=0, product of roots is',options:['−10','7','10','−7'],answer:2,type:'MCQ',marks:1,chapter:'Quadratic Equations',explanation:'Product=c/a=10.'},
{text:'The 10th term of 3,7,11,... is',options:['35','39','43','47'],answer:1,type:'MCQ',marks:1,chapter:'Arithmetic Progressions',explanation:'3+9×4=39.'},
{text:'If similar triangles have side ratio 3:5, their area ratio is',options:['3:5','6:10','9:25','27:125'],answer:2,type:'MCQ',marks:1,chapter:'Triangles',explanation:'Area ratio is square of side ratio.'},
{text:'Distance between (2,3) and (5,7) is',options:['4','5','6','7'],answer:1,type:'MCQ',marks:1,chapter:'Coordinate Geometry',explanation:'√(9+16)=5.'},
{text:'If tan θ=1 and θ is acute, θ=',options:['30°','45°','60°','90°'],answer:1,type:'MCQ',marks:1,chapter:'Introduction to Trigonometry',explanation:'tan45°=1.'},
{text:'A tangent is perpendicular to the radius at the point of',options:['centre','contact','diameter','intersection'],answer:1,type:'MCQ',marks:1,chapter:'Circles',explanation:'Radius to point of contact is perpendicular to tangent.'},
{text:'Probability of an impossible event is',options:['0','1','1/2','−1'],answer:0,type:'MCQ',marks:1,chapter:'Probability',explanation:'Impossible events have probability zero.'}],
Science:[
{text:'Formation of a gas can indicate',options:['chemical reaction','only melting','only cutting','no change'],answer:0,type:'MCQ',marks:1,chapter:'Chemical Reactions',explanation:'Gas evolution is a common sign of chemical change.'},
{text:'A solution of pH 2 is',options:['strongly acidic','weakly acidic','neutral','basic'],answer:0,type:'MCQ',marks:1,chapter:'Acids Bases and Salts',explanation:'Lower pH means greater acidity.'},
{text:'Which metal is stored under kerosene?',options:['Copper','Sodium','Iron','Silver'],answer:1,type:'MCQ',marks:1,chapter:'Metals and Non-metals',explanation:'Sodium reacts vigorously with air and water.'},
{text:'−COOH is the functional group of',options:['alcohols','aldehydes','carboxylic acids','ketones'],answer:2,type:'MCQ',marks:1,chapter:'Carbon Compounds',explanation:'−COOH is carboxyl.'},
{text:'Energy from food is released by',options:['respiration','transpiration','excretion','diffusion'],answer:0,type:'MCQ',marks:1,chapter:'Life Processes',explanation:'Respiration releases usable energy.'},
{text:'The brain part coordinating balance is',options:['cerebrum','cerebellum','medulla','hypothalamus'],answer:1,type:'MCQ',marks:1,chapter:'Control and Coordination',explanation:'Cerebellum coordinates balance and movement.'},
{text:'Binary fission is',options:['sexual','asexual','pollination','fertilisation'],answer:1,type:'MCQ',marks:1,chapter:'Reproduction',explanation:'One organism divides into offspring.'},
{text:'A heterozygous expressed trait is generally',options:['recessive','dominant','acquired','mutated'],answer:1,type:'MCQ',marks:1,chapter:'Heredity',explanation:'A dominant allele is expressed in a heterozygote.'},
{text:'Myopia is corrected using a',options:['convex lens','concave lens','mirror','prism'],answer:1,type:'MCQ',marks:1,chapter:'Human Eye',explanation:'Concave lens diverges rays.'},
{text:'If V doubles and R stays constant, I',options:['halves','doubles','is zero','unchanged'],answer:1,type:'MCQ',marks:1,chapter:'Electricity',explanation:'Ohm law: I=V/R.'}],
'Social Science':[
{text:'A major force behind nineteenth-century nation-states was',options:['nationalism','feudalism','isolation','serfdom'],answer:0,type:'MCQ',marks:1,chapter:'The Rise of Nationalism in Europe',explanation:'Nationalism shaped nation-state formation.'},
{text:'Non-Cooperation Movement was led by',options:['Gandhi','Nehru','Bose','Ambedkar'],answer:0,type:'MCQ',marks:1,chapter:'Nationalism in India',explanation:'Gandhi launched the movement in 1920.'},
{text:'Print culture encouraged',options:['debate and ideas','only secrecy','only maps','less communication'],answer:0,type:'MCQ',marks:1,chapter:'Print Culture',explanation:'Print widened access to ideas and debate.'},
{text:'Renewable/non-renewable describes resource',options:['exhaustibility','ownership','colour','location'],answer:0,type:'MCQ',marks:1,chapter:'Resources and Development',explanation:'It describes ability to replenish.'},
{text:'Intensive subsistence farming is associated with',options:['high population pressure','deserts only','nomadic herding','plantations only'],answer:0,type:'MCQ',marks:1,chapter:'Agriculture',explanation:'It is intensive where population pressure is high.'},
{text:'Power sharing can',options:['reduce conflict','end elections','remove diversity','increase monopoly'],answer:0,type:'MCQ',marks:1,chapter:'Power Sharing',explanation:'Sharing power accommodates social differences.'},
{text:'Federalism divides power among',options:['levels of government','only courts','only parties','only citizens'],answer:0,type:'MCQ',marks:1,chapter:'Federalism',explanation:'Power is constitutionally divided across levels.'},
{text:'Political parties primarily',options:['contest elections','run courts','print money','conduct censuses'],answer:0,type:'MCQ',marks:1,chapter:'Political Parties',explanation:'Parties contest elections and seek to form government.'},
{text:'Per capita income equals total income divided by',options:['population','area','exports','industries'],answer:0,type:'MCQ',marks:1,chapter:'Development',explanation:'It is average income per person.'},
{text:'A formal source of credit is',options:['bank','moneylender','friend','trader'],answer:0,type:'MCQ',marks:1,chapter:'Money and Credit',explanation:'Banks are formal credit institutions.'}],
English:[
{text:'Reported speech: Riya said, “I am preparing.”',options:['Riya said that she was preparing.','Riya said I am preparing.','Riya says she was preparing.','Riya said she prepare.'],answer:0,type:'Grammar',marks:1,chapter:'Grammar',explanation:'Present continuous shifts to past continuous after a past reporting verb.'},
{text:'A “hush” means',options:['noise','silence','crowd','movement'],answer:1,type:'Reading',marks:1,chapter:'Reading Skills',explanation:'Hush means quiet or silence.'},
{text:'A formal letter should be',options:['slang-heavy','clear and respectful','purely comic','confessional'],answer:1,type:'Writing',marks:1,chapter:'Writing Skills',explanation:'Formal writing needs an appropriate register.'},
{text:'In a comedy, repeated exaggerated arguments can create',options:['comic conflict','scientific proof','a map','a biography'],answer:0,type:'Literature',marks:1,chapter:'First Flight',explanation:'Exaggerated conflict is a common comic device.'},
{text:'Literary inference should be based on',options:['textual evidence','guesswork','rumours','outside assumptions'],answer:0,type:'Reading',marks:1,chapter:'Footprints Without Feet',explanation:'Interpretations should be supported by the text.'}],
French:[
{text:'Nous ___ au marché.',options:['allons','allez','vont','vais'],answer:0,type:'MCQ',marks:1,chapter:'Grammaire',explanation:'Nous + aller = allons.'},
{text:'Negative: Il mange du pain.',options:['Il ne mange pas de pain.','Il ne mange du pas pain.','Il pas mange pain.','Il ne pas mange du pain.'],answer:0,type:'MCQ',marks:1,chapter:'Grammaire',explanation:'du changes to de after ne...pas.'},
{text:'Depuis deux ans indicates',options:['continuity from past','future only','one instant','command'],answer:0,type:'MCQ',marks:1,chapter:'Communication',explanation:'Depuis indicates duration continuing from the past.'},
{text:'Paris est ___ que Lyon.',options:['plus grand','plus grande','plus grands','plus grandes'],answer:0,type:'MCQ',marks:1,chapter:'Grammaire',explanation:'Paris is masculine singular.'},
{text:'A notice should be',options:['clear and concise','very long','only English','without purpose'],answer:0,type:'Production écrite',marks:1,chapter:'Production écrite',explanation:'A notice communicates essential information concisely.'}],
'Artificial Intelligence':[
{text:'The AI Project Cycle stage that defines the problem is',options:['Problem Scoping','Modelling','Evaluation','Deployment'],answer:0,type:'MCQ',marks:1,chapter:'AI Project Cycle',explanation:'Problem Scoping identifies the problem, goals and stakeholders.'},
{text:'Examples used to teach a model are',options:['training data','hardware','noise','outputs only'],answer:0,type:'MCQ',marks:1,chapter:'Data Literacy',explanation:'Training data is used for learning patterns.'},
{text:'Recognising objects in photographs is',options:['computer vision','NLP','word processing','networking'],answer:0,type:'MCQ',marks:1,chapter:'Computer Vision',explanation:'Computer vision handles visual information.'},
{text:'NLP deals primarily with',options:['human language','circuits','soil','gears'],answer:0,type:'MCQ',marks:1,chapter:'NLP',explanation:'Natural Language Processing handles human language.'},
{text:'Good training performance but poor unseen-data performance suggests',options:['overfitting','perfect generalisation','encryption','hardware failure'],answer:0,type:'MCQ',marks:1,chapter:'Evaluation',explanation:'Overfitting means learning training data too specifically.'},
{text:'Responsible AI practice includes',options:['informed consent','publicly sharing private data','ignoring bias','collecting everything'],answer:0,type:'MCQ',marks:1,chapter:'Data Literacy',explanation:'Consent and privacy are core responsible-data practices.'}]};